### PR TITLE
use UnoObject in place of Object to avoid issue passing to action

### PR DESCRIPTION
**Pull request by cbaggers**

### CODE REVIEW

**Comment by knatten** [comment]
This should probably not be merged, as we're waiting for a foreign code fix instead https://fusetools.slack.com/archives/uno/p1476348508001634

**Comment by cbaggers** [comment]
Change of plan! The second commit is useful. A nice thing with `delegate`s, `Action`s and `Func`s in foreign java is that they get their own `run` method. So you don't need to pass them back to call them.

See [here](https://github.com/fusetools/fuse-samples/blob/e9c676346fbc8da294ff05b32e8f2f00344590d4/Samples/NativeDialogs/Fuse.Dialogs/Dialogs.uno#L288) for an example

**Comment by knatten** [comment]
Let me know as soon as this is merged, then I'll try to make samples great^wgreen again on TC.

**Comment by kristianhasselknippe** [comment]
cherry-picked the second commit, so i'm closing this. Sorry for taking so long :S

**Pull request closed without merging**
