### PR TITLE
Enhancement: flat folder structure

### PR DESCRIPTION
**Pull request by eksperts**

### CODE REVIEW

**Comment by mortoray** [comment]
There is at least one link from fuselibs to a fuse-sample, in Transition.uno

**Comment by mortoray** [comment]
Be aware of the pending PRs when merging this. They need to be modified as well if not flat.

**Comment by eksperts** [comment]
yes, links to this repo will likely be broken, if any. not entirely sure how to cover that.
the other pending PR #42 does not affect any examples that were moved.

**Comment by eksperts** [comment]
I found that my fork was outdated, updating and pushing another commit

**Comment by kristianhasselknippe** [comment]
will put this on hold for a little bit to see if it's worth the trouble

**Pull request closed without merging**
